// Generated by CoffeeScript 1.9.0
(function() {
  exports.initConst = function() {
    global.TBL_USER = "tbl_user";
    return global.TBL_BUILDING = "tbl_building";
  };

}).call(this);

//# sourceMappingURL=constHelper.js.map
