// Generated by CoffeeScript 1.9.0
(function() {
  exports.initConst = function() {
    global.TBL_USER = "user";
    return global.TBL_BUILDING = "site";
  };

}).call(this);

//# sourceMappingURL=constHelper.js.map
