// Generated by CoffeeScript 1.9.0
(function() {
  exports.hapiOptions = {
    connections: {
      routes: {
        cors: true
      }
    }
  };

  exports.app = {
    name: "umanji-api",
    host: "localhost",
    port: 8080
  };

}).call(this);

//# sourceMappingURL=hapiConfig.js.map
