// Generated by CoffeeScript 1.9.0
(function() {
  exports.initOptions = function(app) {
    app.connection({
      host: "0.0.0.0",
      port: 8080,
      routes: {
        cors: true
      }
    });
    return global.appEnv = {
      path: require("app-root-path"),
      apiPath: require("app-root-path") + "/api"
    };
  };

  exports.initRoutes = function(app, isAutoLoad) {
    var apiFiles, file, fs, path, _i, _len, _results;
    fs = require("fs");
    path = require("path");
    apiFiles = fs.readdirSync(appEnv.apiPath);
    if (isAutoLoad) {
      _results = [];
      for (_i = 0, _len = apiFiles.length; _i < _len; _i++) {
        file = apiFiles[_i];
        _results.push((function(file) {
          var filePath;
          if (path.extname(file) === ".coffee") {
            filePath = global.appEnv.apiPath + "/" + file;
            (require(filePath)).loadIndex(app);
            return console.log(filePath);
          }
        })(file));
      }
      return _results;
    } else {
      require(appEnv.apiPath + "/hello.coffee").loadIndex(app);
      require(appEnv.apiPath + "/world.coffee").loadIndex(app);
      return require(appEnv.apiPath + "/user.coffee").loadIndex(app);
    }
  };

}).call(this);

//# sourceMappingURL=hapiHelper.js.map
