// Generated by CoffeeScript 1.9.0
(function() {
  exports.initApp = function() {
    return global.app = {
      path: require("app-root-path"),
      host: "localhost",
      port: 8080,
      serviceDir: "service"
    };
  };

  exports.initHapi = function(demon) {
    return demon.connection({
      host: app.host,
      port: app.port
    });
  };

  exports.initHapiRouting = function(demon) {
    var file, fs, path, serviceFiles, servicePath, _i, _len, _results;
    fs = require("fs");
    path = require("path");
    servicePath = app.path + "/" + app.serviceDir;
    serviceFiles = fs.readdirSync(servicePath);
    _results = [];
    for (_i = 0, _len = serviceFiles.length; _i < _len; _i++) {
      file = serviceFiles[_i];
      _results.push((function(file) {
        var filePath;
        if (path.extname(file) === ".coffee") {
          filePath = servicePath + "/" + file;
          return (require(filePath)).loadIndex(demon);
        }
      })(file));
    }
    return _results;
  };

}).call(this);

//# sourceMappingURL=initHelper.js.map
