// Generated by CoffeeScript 1.9.0
(function() {
  exports.initNode = function() {
    return global.app = {
      path: require('app-root-path'),
      host: 'localhost',
      port: 8080
    };
  };

  exports.initHapi = function(demon) {
    return demon.connection({
      host: app.host,
      port: app.port
    });
  };

  exports.initHapiRouter = function(demon) {
    console.log('app.path: ' + app.path);
    console.log('app.host: ' + app.host);
    return console.log('app.port: ' + app.port);
  };

}).call(this);

//# sourceMappingURL=initHelper.js.map
