// Generated by CoffeeScript 1.9.0
(function() {
  var mysql;

  mysql = require("mysql");

  exports.initDbms = function() {
    var config, pool;
    config = {
      host: "localhost",
      port: 3306,
      user: "umanji",
      password: "18281828",
      database: "master1",
      connectionLimit: 20,
      waitForConnections: false
    };
    pool = mysql.createPool(config);
    return pool.getConnection(function(error, conn) {
      var qry;
      qry = "select * from tbl_user";
      return conn.query(qry, function(err, res) {
        if (err) {
          console.log("QRY ERROR: " + qry);
        }
        return console.log(res);
      });
    });
  };

}).call(this);

//# sourceMappingURL=mysqlHelper.js.map
