// Generated by CoffeeScript 1.9.0
(function() {
  var mysql;

  mysql = require("mysql");

  exports.initDbms = function() {
    var config;
    config = {
      host: "localhost",
      port: 3306,
      user: "umanji",
      password: "18281828",
      database: "master1",
      connectionLimit: 20,
      waitForConnections: false
    };
    return global.mysqlPool = mysql.createPool(config);
  };

  exports.getRecords = function(table) {
    var sql;
    sql = "select * from " + table;
    return mysqlPool.getConnection(function(err, conn) {
      return conn.query(sql, function(err, rows) {
        if (err) {
          conn.release();
          console.log(err);
          throw err;
        }
        console.log(rows);
        return conn.release();
      });
    });
  };

}).call(this);

//# sourceMappingURL=mysqlHelper.js.map
