// Generated by CoffeeScript 1.9.0
(function() {
  var app, hapi, hapiHelper;

  hapi = require("hapi");

  hapiHelper = require("./helper/hapiHelper.coffee");

  app = new hapi.Server();

  hapiHelper.initOptions(app);

  hapiHelper.initRoutes(app, true);

  app.start();

  console.log("========================================");

  console.log("Server started..");

  console.log(new Date().toString());

  console.log(app.info.uri);

  console.log("========================================");

}).call(this);

//# sourceMappingURL=app.js.map
