// Generated by CoffeeScript 1.9.0
(function() {
  var demon, hapi, initHelper;

  hapi = require("hapi");

  initHelper = require("./helper/initHelper.coffee");

  initHelper.initApp();

  demon = new hapi.Server();

  initHelper.initHapi(demon);

  initHelper.initHapiRouting(demon);

  demon.start();

  console.log("========================================");

  console.log("umanji server started..");

  console.log(new Date().toString());

  console.log(demon.info.uri);

  console.log("========================================");

}).call(this);

//# sourceMappingURL=app.js.map
