// Generated by CoffeeScript 1.9.0
(function() {
  exports.hello.index = function(demon) {
    return demon.route({
      method: 'GET',
      path: '/api/hello',
      handler: function(request, reply) {
        return reply('HELLO');
      }
    });
  };

}).call(this);

//# sourceMappingURL=hello.js.map
