// Generated by CoffeeScript 1.9.0
(function() {
  var hello;

  exports.loadIndex = function(demon) {
    return demon.route({
      method: "GET",
      path: "/api/hello",
      handler: function(request, reply) {
        return hello(request, reply);
      }
    });
  };

  hello = function(request, reply) {
    return reply("HELLO");
  };

}).call(this);

//# sourceMappingURL=hello.js.map
