// Generated by CoffeeScript 1.9.0
(function() {
  exports.world.index = function(demon) {
    return demon.route({
      method: 'GET',
      path: '/api/world',
      handler: function(request, reply) {
        return reply('WORLD');
      }
    });
  };

}).call(this);

//# sourceMappingURL=world.js.map
