// Generated by CoffeeScript 1.9.0
(function() {
  var deleteBuilding, getBuilding, postBuilding, putBuilding;

  exports.loadIndex = function(app) {
    var indexList;
    indexList = [
      {
        method: "POST",
        path: "/buildings",
        handler: postBuilding
      }, {
        method: "GET",
        path: "/buildings/{id}",
        handler: getBuilding
      }, {
        method: "PUT",
        path: "/buildings/{id}",
        handler: putBuilding
      }, {
        method: "DELETE",
        path: "/buildings/{id}",
        handler: deleteBuilding
      }
    ];
    return app.route(indexList);
  };

  postBuilding = function(req, reply) {
    return reply({
      "result": "POST BUILDING"
    });
  };

  getBuilding = function(req, reply) {
    return reply({
      "result": "GET BUILDING"
    });
  };

  putBuilding = function(req, reply) {
    return reply({
      "result": "PUT BUILDING"
    });
  };

  deleteBuilding = function(req, reply) {
    return reply({
      "result": "DELETE BUILDING"
    });
  };

}).call(this);

//# sourceMappingURL=building.js.map
