// Generated by CoffeeScript 1.9.0
(function() {
  var deleteHello, getHello, postHello, putHello;

  exports.loadIndex = function(app) {
    var indexList;
    indexList = [
      {
        method: "POST",
        path: "/hello",
        handler: postHello
      }, {
        method: "GET",
        path: "/hello/{id}",
        handler: getHello
      }, {
        method: "PUT",
        path: "/hello/{id}",
        handler: putHello
      }, {
        method: "DELETE",
        path: "/hello/{id}",
        handler: deleteHello
      }
    ];
    return app.route(indexList);
  };

  postHello = function(req, reply) {
    return reply({
      "result": "POST HELLO"
    });
  };

  getHello = function(req, reply) {
    return reply({
      "result": "GET HELLO"
    });
  };

  putHello = function(req, reply) {
    return reply({
      "result": "PUT HELLO"
    });
  };

  deleteHello = function(req, reply) {
    return reply({
      "result": "DELETE HELLO"
    });
  };

}).call(this);

//# sourceMappingURL=hello.js.map
