// Generated by CoffeeScript 1.9.0
(function() {
  var deleteUser, getUser, postUser, putUser;

  exports.loadIndex = function(app) {
    var indexList;
    indexList = [
      {
        method: "POST",
        path: "/users",
        handler: postUser
      }, {
        method: "GET",
        path: "/users/{id}",
        handler: getUser
      }, {
        method: "PUT",
        path: "/users/{id}",
        handler: putUser
      }, {
        method: "DELETE",
        path: "/users/{id}",
        handler: deleteUser
      }
    ];
    return app.route(indexList);
  };

  postUser = function(req, reply) {
    return reply({
      "result": "POST USER"
    });
  };

  getUser = function(req, reply) {
    return reply({
      "result": "GET USER"
    });
  };

  putUser = function(req, reply) {
    return reply({
      "result": "PUT USER"
    });
  };

  deleteUser = function(req, reply) {
    return reply({
      "result": "DELETE USER"
    });
  };

}).call(this);

//# sourceMappingURL=user.js.map
