// Generated by CoffeeScript 1.9.0
(function() {
  var world;

  exports.loadIndex = function(app) {
    return app.route({
      method: "GET",
      path: "/world",
      handler: function(req, reply) {
        return world(req, reply);
      }
    });
  };

  world = function(req, reply) {
    return reply("WORLD");
  };

}).call(this);

//# sourceMappingURL=world.js.map
