// Generated by CoffeeScript 1.9.0
(function() {
  var deleteWorld, getWorld, postWorld, putWorld;

  exports.loadIndex = function(app) {
    var indexList;
    indexList = [
      {
        method: "POST",
        path: "/world",
        handler: postWorld
      }, {
        method: "GET",
        path: "/world/{id}",
        handler: getWorld
      }, {
        method: "PUT",
        path: "/world/{id}",
        handler: putWorld
      }, {
        method: "DELETE",
        path: "/world/{id}",
        handler: deleteWorld
      }
    ];
    return app.route(indexList);
  };

  postWorld = function(req, reply) {
    return reply({
      "result": "POST WORLD OK"
    });
  };

  getWorld = function(req, reply) {
    return reply({
      "result": "GET WORLD OK"
    });
  };

  putWorld = function(req, reply) {
    return reply({
      "result": "PUT WORLD OK"
    });
  };

  deleteWorld = function(req, reply) {
    return reply({
      "result": "DELETE WORLD OK"
    });
  };

}).call(this);

//# sourceMappingURL=world.js.map
