// Generated by CoffeeScript 1.9.0
(function() {
  var del, get, getList, post, put;

  exports.loadIndex = function(app) {
    var indexList;
    indexList = [
      {
        method: "POST",
        path: "/world",
        handler: post
      }, {
        method: "GET",
        path: "/world",
        handler: getList
      }, {
        method: "GET",
        path: "/world/{id}",
        handler: get
      }, {
        method: "PUT",
        path: "/world/{id}",
        handler: put
      }, {
        method: "DELETE",
        path: "/world/{id}",
        handler: del
      }
    ];
    return app.route(indexList);
  };

  post = function(req, reply) {
    return reply({
      "result": "POST"
    });
  };

  getList = function(req, reply) {
    return reply({
      "result": "GET LIST"
    });
  };

  get = function(req, reply) {
    return reply({
      "result": "GET"
    });
  };

  put = function(req, reply) {
    return reply({
      "result": "PUT"
    });
  };

  del = function(req, reply) {
    return reply({
      "result": "DELETE"
    });
  };

}).call(this);

//# sourceMappingURL=world.js.map
